# Generated by Django 5.1 on 2024-08-31 19:33

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0002_category_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=timezone.now, verbose_name="Дата производства продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="Catalog.category",
            ),
        ),
    ]
