# Generated by Django 5.1 on 2024-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0003_product_manufactured_at_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(verbose_name="Дата производства продукта"),
        ),
    ]
