# Generated by Django 5.1 on 2024-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="просмотры"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата создания(записи в БД)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения(записи в БД)"
            ),
        ),
    ]
