# Generated by Django 5.1 on 2024-09-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0004_product_views_count_alter_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(default=1, verbose_name="Номер версии"),
                ),
                (
                    "name_version",
                    models.CharField(max_length=20, verbose_name="Имя версии"),
                ),
                (
                    "current_version",
                    models.BooleanField(
                        default=True, verbose_name="Признак текущей версии"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_versions",
                        to="Catalog.product",
                    ),
                ),
            ],
        ),
    ]
