# Generated by Django 5.1 on 2024-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0005_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": [
                    "product",
                    "version_number",
                    "name_version",
                    "current_version",
                ],
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Продается"),
        ),
    ]
