# Generated by Django 5.1 on 2024-09-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "name",
                    "purchase_price",
                    "category",
                    "created_at",
                    "is_active",
                    "owner",
                ],
                "permissions": [
                    ("can_edit_description", "Может менять описание Продукта"),
                    ("can_edit_category", "Может менять категорию любого продукта"),
                    ("can_edit_toogle", "Может отменять публикацию продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
